### ISSUE TITLE
Support for complex entities?

### ISSUE THREAD

**Issue by Drahness** [Aperocky/sqlitedao#1]
I was wondering if it is posible to add suport to entities with relationships or complex attributes.

**Comment by Aperocky** [comment]
Can you expand what you mean by complex attributes and relationships? `sqlite` table only supports 5 raw data types and it is really up to the DAO and custom classes to make extensions. TableItems should allow any extrapolations.

**Comment by cmflynn** [comment]
sup rocky! 

probably means relationships in an RDMS sense. so for example, a foreign key between two models in a traditional ORM.

**Comment by Aperocky** [comment]
SUP!!!

I'll add FOREIGN KEY and UNIQUE INDEX support on the next version.

**Comment by Aperocky** [comment]
Sup Cody!

That sounds spicy and beyond pet scale, but I can try adding UNIQUE INDEX and FOREIGN KEY to the next patch. It does almost feel a feature to not have intermingled tables, though it might be that I've worked with nosql too much.

**Comment by Aperocky** [comment]
Going to close this as the goal of this package is to have a ultra-light weight, personal project oriented ORM. adding complext attribute/relationship is not a high priority and may run contrary to goal of this package.
